application: gophers-london
version: 2
runtime: go
api_version: go1
skip_files:
- LICENSE
- README
- ^.git
- .idea/workspace.xml
- .idea/misc.xml
- .idea/libraries
handlers:
- url: /.*
  script: _go_app
